lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", UserController, :index
    resources "/meow", MeowController, except: [:show, :edit, :delete, :update]
    resources "/stalk", StalkController, except: [:show, :edit]
    resources "/user", UserController, except: [:delete, :edit]

    post "/icon", IconController, :create
    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout
  end
  
  # Other scopes may use custom stacks.
  scope "/api", MicroblogWeb do
    pipe_through :api
    resources "/like", LikeController, except: [:new, :edit]
  end
end

lib/microblog/micro_blog/user.ex
defmodule Microblog.MicroBlog.User do
  use Arc.Ecto.Schema
  use Ecto.Schema
  import Ecto.Changeset
  alias Microblog.MicroBlog.User

  schema "user" do
    field :email, :string
    field :first_name, :string
    field :handle, :string
    field :last_name, :string
    #<From Nat's Lecture Notes>
    field :password_hash, :string
    field :pw_tries, :integer
    field :pw_last_try, :utc_datetime
    field :password, :string, virtual: true
    field :icon, Microblog.Icon.Type
    #</From Nat's Lecture Notes>
    has_many(:meows, Microblog.MicroBlog.Meow)
    timestamps()
  end

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:email, :handle, :first_name, :last_name, :password, :icon])
    |> cast_attachments(attrs,[:icon])
    |> validate_required([:email, :handle, :first_name, :last_name, :password])
    #From Nat's Lecture Notes
    |> validate_password(:password)
    |> put_pass_hash()
    |> validate_required([:email, :handle, :first_name, :last_name, :password_hash])
  end
  def changeset_updateOnly(%User{} = user, attrs) do
    user
    |> cast(attrs, [:email, :handle, :first_name, :last_name, :password, :icon])
    |> cast_attachments(attrs,[:icon])
    |> validate_required([:email, :handle, :first_name, :last_name])
  end
  # Password validation
  # From Comeonin docs (From Nat's Class Notes)
  def validate_password(changeset, field, options \\ []) do
    IO.puts("Got into validate-password")
    validate_change(changeset, field, fn _, password ->
      case valid_password?(password) do
        {:ok, _} -> []
        {:error, msg} -> [{field, options[:message] || msg}]
      end
    end)
  end

  def put_pass_hash(%Ecto.Changeset{valid?: true, changes: %{password: password}} = changeset) do
    IO.puts("Saving Password")
    changes = Comeonin.Pbkdf2.add_hash(password)
    result = change(changeset, changes)
    result
  end
  def put_pass_hash(changeset), do: changeset

  def valid_password?(password) when byte_size(password) > 7 do
    IO.puts("Validated")
    {:ok, password}
  end
  def valid_password?(password) do
      IO.puts("Failed"<>Integer.to_string(byte_size(password)))
     {:error, "The password is too short"}
  end
end

lib/microblog_web/controllers/user_controller.ex
defmodule MicroblogWeb.UserController do
  use MicroblogWeb, :controller

  alias Microblog.MicroBlog
  alias Microblog.MicroBlog.User

  def index(conn, _params) do
    user = MicroBlog.list_user()
    render(conn, "index.html", user: user)
  end

  def new(conn, _params) do
    changeset = MicroBlog.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case MicroBlog.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    int_id = String.to_integer(id)
    posts = Microblog.MicroBlog.get_meows_to_display_for_user(int_id)
    # posts = MicroBlog.get_meows_for_user(int_id)
    user = MicroBlog.get_user!(id)
    render(conn, "show.html", user: user, posts: posts)
  end

  def edit(conn, %{"id" => id}) do
    user = MicroBlog.get_user!(id)
    changeset = MicroBlog.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = MicroBlog.get_user!(id)

    case MicroBlog.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = MicroBlog.get_user!(id)
    {:ok, _user} = MicroBlog.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end

lib/microblog_web/views/user_view.ex
defmodule MicroblogWeb.UserView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/microblog_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>
  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= text_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :handle, class: "control-label" %>
    <%= text_input f, :handle, class: "form-control" %>
    <%= error_tag f, :handle %>
  </div>

  <div class="form-group">
    <%= label f, :first_name, class: "control-label" %>
    <%= text_input f, :first_name, class: "form-control" %>
    <%= error_tag f, :first_name %>
  </div>

  <div class="form-group">
    <%= label f, :last_name, class: "control-label" %>
    <%= text_input f, :last_name, class: "form-control" %>
    <%= error_tag f, :last_name %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/microblog_web/templates/user/index.html.eex
<h2>Listing User</h2>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Handle</th>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @user do %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.handle %></td>
      <td><%= user.first_name %> <%= user.last_name %></td>

      <td class="text-right">
        <span><%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New User", to: user_path(@conn, :new) %></span>

lib/microblog_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/microblog_web/templates/user/show.html.eex
<div class="container">
    <div class="row justify-content-center">
        <div class="col-4">
            <div class="row mb-3">
                <%= if(@user.icon) do %>
                    <div class="col-md-6">
                        <img width="100" src=<%="/uploads/" <> @user.icon.file_name %>/>
                    </div>
                <% else %>
                    <div class="col-md-6"><i style="font-size: 7rem" class="fa fa-user" aria-hidden="true"></i></div>
                <% end %>

                <%= if( @current_user != nil && @current_user.id == @user.id ) do %>
                    <%= form_for @conn, icon_path(@conn, :create),[multipart: true, as: "icon", id: "icon_form"], fn f -> %>
                         <label>Change Icon</lable>
                         <%= file_input f, :icon, id: "icon_file" %>
                    <%end%>
                <%end%>
                
                <div class="col-md-6 row">
                    <span class="col-md-12"><%= @user.first_name %> <%= @user.last_name %></span>
                    <span class="col-md-12">@<%= @user.handle %></span>
                    <%# <span class="d-none d-md-block col-md-12">Last Meow: 20min ago</span> %>
                    <%= if( @current_user != nil && @current_user.id != @user.id )do %>
                        <%= form_for @conn, stalk_path(@conn, :create),[as: "stalk"], fn f -> %>
                            <%= hidden_input f, :actor_id, value: @current_user.id %>
                            <%= hidden_input f, :target_id, value: @user.id %>
                            <%= submit "Follow", class: "btn btn-info" %>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="col-12">
            <%= if( @current_user != nil && @current_user.id == @user.id ) do %>
                <div class="card mb-4 bg-light">
                    <div class="card-body">
                        <%= form_for @conn, meow_path(@conn, :create),[as: "meow_vm", id: "post_form"], fn f -> %>
                            <div class="input-group w-100">
                                <button class="btn btn-success input-group-addon"><i class="fa fa-edit" aria-hidden="true"></i></button>
                                <%= textarea f, :content, class: "form-control", placeholder: "Post", rows: 5 %>
                                <%= submit id: "submit-post", class: "btn btn-primary input-group-addon" do %>
                                    <i class="fa fa-send-o" aria-hidden="true"></i>
                                </div>
                                <% end %>
                                <%= hidden_input f, :author_id, value: @current_user.id%>
                        <% end %>
                    </div>
            <% end %>
                </div>

                <!-- Begin -->
                <section id="post_section">
                    <div rv-each-post="posts" class="card mb-2">
                        <div class="card-body">
                            <div class="card-title d-flex flex-nowrap">
                                <div class="d-flex mr-auto flex-wrap flex-md-row flex-column">
                                    <span class="user-name p-md-2">{post.author.first} {post.author.last}</span>
                                    <span class="user-handle p-md-2">@{post.author.handle}</span>
                                </div>
                                <span class="d-flex">
                                <%# csrf token trick from:  https://stackoverflow.com/a/40605374 %>
                                        <span rv-on-click="post.likers.clicked" class="clickable like" rv-data-post="post.id"
                                             <%= if( @current_user != nil )do %>
                                             data-user="<%=@current_user.id%>"
                                             <%end%>
                                             data-csrf="<%= raw Plug.CSRFProtection.get_csrf_token() %>">
                                            {post.likers.count} <i class="fa fa-paw" aria-hidden="true"></i>
                                            <div class="d-none d-md-block">
                                                <div class="popover d-none">
                                                    <ul>
                                                        <li rv-each-user="post.likers.list">@{user.actor.handle}</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </span>
                                </span>
                            </div>
                            
                            <div rv-html="post.content" class="card-text">
                                <%# { post.content } %>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="input-group w-100">
                                <input type="text" class="form-control" placeholder="Reply...">
                                <span class="btn btn-primary input-group-addon"><i class="fa fa-send-o" aria-hidden="true"></i></span>
                            </div>
                        </div>
                    </div>
                    <!-- end -->
                </section>
            </div>
        </div>
    </div>
</div>
<script>
    window.currentUserPageId = <%=@user.id %>;
</script>