lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs
  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", UserController, :index
    resources "/meow", MeowController, except: [:show, :edit, :delete, :update]
    resources "/stalk", StalkController, except: [:show, :edit]
    resources "/user", UserController, except: [:delete, :edit]

    post "/icon", IconController, :create
    post "/sessions", SessionController, :login
    delete "/sessions", SessionController, :logout
  end
  
  # Other scopes may use custom stacks.
  scope "/api", MicroblogWeb do
    pipe_through :api
    resources "/like", LikeController, except: [:new, :edit]
  end
end

lib/microblog_web/views/layout_view.ex
defmodule MicroblogWeb.LayoutView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Litterbox</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    
    <div class="container">
      <header class="header has-top-bar">
          <nav class="nav navbar navbar-dark bg-info navbar-expand-md fixed-top">
            <%= if @current_user do %>
                <%= link to: user_path(@conn, :show, @current_user.id), class: "navbar-brand" do %>
                    <i class="fa fa-paw" aria-hidden="true"></i>
                <% end %>
            <% else %>
                <%= link to: user_path(@conn, :index), class: "navbar-brand" do %>
                    <i class="fa fa-paw" aria-hidden="true"></i>
                <% end %>
            <% end %>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main-navbar">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse not-full-basis" id="main-navbar">
                <ul class="navbar-nav mr-auto text-center">
                    <%= if @current_user do %>
                        <li class="nav-item">
                            <%# From Nat's Notes, see Helper.ex for details %>
                            <% active = isActive(@view_module,@view_template, "Stalk", "index") %>
                            <%= link "Stalking", to: stalk_path(@conn, :index), class: "nav-link #{active}" %>
                        </li>
                    <% end %>
                    <li class="nav-item">
                        <%# From Nat's Notes, see Helper.ex for details %>
                        <% active = isActive(@view_module,@view_template, "User", "index") %>
                        <%= link to: user_path(@conn, :index), class: "nav-link #{active}" do %>
                            <i class="fa fa-globe" aria-hidden="true"></i> Explore
                        <% end %>
                    </li>
                    <li class="nav-item">
                        <span class="d-block d-md-none">
                            <%= link("logout", to: session_path(@conn, :logout), class: "nav-link font-weight-bold", method: :delete) %>
                        </span>
                    </li>
                    <li class="nav-item d-block d-md-none w-100">
                        <form class="form-inline">
                            <div class="input-group w-100">
                                <input type="text" class="form-control" placeholder="Search"> %>
                                <span class="search input-group-addon btn-primary"><i class="fa fa-user" aria-hidden="true"></i></span>
                            </div>
                        </form>
                    </li>
                </ul>
            </div>
            
            <form class="form-inline d-none d-md-flex mr-auto ml-auto">
                <div class="input-group">            
                    <input type="text" class="form-control" placeholder="Search">
                    <span class="search input-group-addon btn-primary"><i class="fa fa-user" aria-hidden="true"></i></span>
                </div>
            </form>

            <%= if @current_user do %>
                <span class="text-light d-none d-md-flex ml-2">
                    <%# <%= @current_user.email %>
                    <%= link("logout", to: session_path(@conn, :logout), class: "btn btn-danger", method: :delete) %>
                </span>
                <% else %>
                <button type="button" class="btn btn-success ml-2" data-toggle="modal" data-target="#loginModal">
                    Login
                </button>
            <% end %>

        </nav>
      </header>

      <%= if get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <div id="loginModal" class="modal fade">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Login</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <%= form_for @conn, session_path(@conn, :login), [as: "user", class: "form p-2", id: "login-form"], fn f -> %>
                        <div class="input-group mb-2">
                            <%= text_input f, :email,  placeholder: "email", class: "form-control" %>
                        </div>
                        <div class="input-group">
                            <%= text_input f, :password,  placeholder: "password", class: "form-control" %>
                        </div>
                    <% end %>
                </div>
                <div class="modal-footer">
                    <button id="login-submit" type="button" class="btn btn-primary">Login</button>
                </div>
            </div>
        </div>
    </div>
    <script>
    $(function(){
        $("#login-submit").click(function(){
            $("#login-form").submit();
        });
        $("#icon_file").change(function(){
            $("#icon_form").submit();
        });
        $(".search").click(function(){
            var term = $(this).siblings('input').first().val()
            document.location = "<%= meow_path(@conn, :index)%>?term="+term;
            console.log("here");
            debugger;
        });
    });
    
    </script>
  </body>
</html>